spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: adminadmin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true # visit localhost:8080 for live H2 console and url is "jdbc:h2:mem:mydb" it's directly manipulating Spring memory in some sense